version: '3'
services:
  hazelcast-node-1:
    build: .
    container_name: hazelcast-node-1
    environment:
      - HZ_NETWORK_JOIN_METHOD=multicast
    networks:
      - hazelcast-network
    entrypoint: ["java", "-cp", "target/matrixMultiplication4-1.0-SNAPSHOT.jar", "org.ulpgc.MatrixMultiplicationNode"]

  hazelcast-node-2:
    build: .
    container_name: hazelcast-node-2
    environment:
      - HZ_NETWORK_JOIN_METHOD=multicast
    networks:
      - hazelcast-network
    entrypoint: ["java", "-cp", "target/matrixMultiplication4-1.0-SNAPSHOT.jar", "org.ulpgc.MatrixMultiplicationNode"]

  hazelcast-node-3:
    build: .
    container_name: hazelcast-node-3
    environment:
      - HZ_NETWORK_JOIN_METHOD=multicast
    networks:
      - hazelcast-network
    entrypoint: ["java", "-cp", "target/matrixMultiplication4-1.0-SNAPSHOT.jar", "org.ulpgc.MatrixMultiplicationNode"]

  matrix-multiplication-client:
    build: .
    container_name: matrix-multiplication-client
    depends_on:
      - hazelcast-node-1
      - hazelcast-node-2
      - hazelcast-node-3
    networks:
      - hazelcast-network
    entrypoint: ["java", "-cp", "target/matrixMultiplication4-1.0-SNAPSHOT.jar", "org.ulpgc.MatrixMultiplicationClient"]

networks:
  hazelcast-network:
    driver: bridge
